version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue-instantsearch
    versions:
    - ">= 2.7.a"
  - dependency-name: vue-svg-loader
    versions:
    - ">= 0.15.0"
  # Version 2 of this package is for Vue3
  - dependency-name: vue-countdown
    versions:
    - ">= 1.1.5"
  # clipboard-copy v4 drops IE11 support
  - dependency-name: clipboard-copy
    versions:
    - ">= 3.2.0"
