# The preview parameter should come from a route query param and
# should not be passed in manually. It is handled by src/api/ContentfulPreviewLink.js
query contentfulEntries(
	$contentType: String!
	$contentKey: String
	$preview: Boolean = false
	$limit: Int
) {
	contentful {
		searchEntries(
			contentType: $contentType
			contentKey: $contentKey
			limit: $limit
		) @skip(if: $preview) {
			total
			skip
			limit
			items {
				entryId
				entry
			}
		}
		searchPreviewEntries(
			contentType: $contentType
			contentKey: $contentKey
			limit: $limit
		) @include(if: $preview) {
			total
			skip
			limit
			items {
				entryId
				entry
			}
		}
	}
}
