query lenderProfileBadgeData(
  $contentType: String!
  $contentKey: String
  $preview: Boolean = false
  $limit: Int
) {
  userAchievementProgress {
    id
    lendingAchievements {
      id
      description
      milestoneProgress {
        earnedAtDate
        id
        milestoneStatus
        progress
        target
      }
    }
    tieredLendingAchievements {
      id
      description
      totalProgressToAchievement
      tiers {
        target
        tierStatement
        completedDate
        learnMoreURL
      }
    }
  }
  contentful {
    searchEntries(
      contentType: $contentType
      contentKey: $contentKey
      limit: $limit
    ) @skip(if: $preview) {
      total
      skip
      limit
      items {
        entryId
        entry
      }
    }
    searchPreviewEntries(
      contentType: $contentType
      contentKey: $contentKey
      limit: $limit
    ) @include(if: $preview) {
      total
      skip
      limit
      items {
        entryId
        entry
      }
    }
  }
  my {
    id
    loans(limit: 50) {
      values {
        id
        name
        image {
          id
          url
        }
      }
    }
  }
}
