query portfolioQuery {
	my {
		id
		givingFundParticipation {
			totalAmount
			totalCount
		}
		# Fund ID must match COLOMBIA_DISASTER_RELIEF
		reliefFundParticipation: givingFundParticipation(
			filter: { fundIds: ["238fe077-033e-4a59-8d11-e571e6e4ed31"] }
		) {
			totalCount
		}
		givingFunds {
			totalCount
		}
		loans(limit: 50) {
			totalCount
			values {
				id
				status
				geocode {
					country {
						id
						name
						region
					}
				}
			}
		}
		teams (
			limit: 100
		) {
			values {
				id
				team {
					id
					name
					teamPublicId
				}
			}
		}
		userPreferences {
			id
			preferences
		}
	}
	general {
		team_challenge_enable: uiConfigSetting(key: "portfolio_team_challenge_enable") {
			key
			value
		}
		challenge_allowed_teams: uiConfigSetting(key: "portfolio_challenge_allowed_teams") {
			key
			value
		}
		goal_in_review_enable: uiConfigSetting(key: "goal_in_review_enable") {
			key
			value
		}
		goal_in_review_in_progress_start: uiConfigSetting(key: "goal_in_review_in_progress_start") {
			key
			value
		}
	}
}
