# build stage
FROM node:16-alpine as build-stage
RUN apk add --no-cache git
RUN apk add --no-cache bash
RUN apk add --no-cache make gcc g++ python2 pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev

RUN mkdir /ui
COPY ./ /ui/
WORKDIR /ui

RUN npm ci

EXPOSE 8888

# Launch application
CMD ["npm","run","docker-dev-vm","--","--config=dev-local"]
