FROM jenkinsci/slave:alpine
MAINTAINER Mike Leach <mike@kiva.org>

# very basic.  could use some improvements.
# hack: adds very old alpine repo so we can grab very old nodejs
# which is still newer than we want (6.7.0 vs 6.11.1)
# alpine jumps from node 4.x to 6.7, between alpine 3.3 and 3.4.

# note: since jenkins always needs jdk, that undermines the smallness
# of alpine somewhat, but we still get an image about 1/3 the size of
# the one based on xenial.

# nodejs version could be made exact by building from source
# here is an example:
# https://github.com/nodejs/docker-node/blob/master/6/alpine/Dockerfile
# the image build process takes a long time though.

USER root
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.4/main' >> /etc/apk/repositories &&\
    apk --update add nodejs==6.7.0-r1 &&\
    npm install -g npm@5.3.0
