FROM alpine

RUN apk add --no-cache nodejs
RUN apk add --no-cache npm
RUN apk add --no-cache git
RUN apk add --no-cache bash
RUN mkdir /ui
COPY ./ /ui/
WORKDIR /ui
# we should switch this to npm ci (need to figure out how to tell Jenkins to maintain some cache of modules first)
RUN npm i --no-save
RUN npm run build
RUN npm prune --production
WORKDIR /ui/ui-build
RUN npm install cross-env
CMD [ "/usr/bin/npm", "start", "--", "--port=8888", "--config=k8sdev", "--prefix", "/ui/ui-build" ]

