export const RECEIVE_LOAN_SEARCH_SUGGESTIONS = 'RECEIVE_LOAN_SEARCH_SUGGESTIONS';
export const RECEIVE_MY_KIVA_INFO = 'RECEIVE_MY_KIVA_INFO';
export const SET_PUBLIC_LEND_MENU_DATA = 'SET_PUBLIC_LEND_MENU_DATA';
export const SIGN_OUT = 'SIGN_OUT';
