export const RECEIVE_LOAN_SEARCH_SUGGESTIONS = 'RECEIVE_LOAN_SEARCH_SUGGESTIONS';
export const RECEIVE_MY_KIVA_INFO = 'RECEIVE_MY_KIVA_INFO';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_LOAN_SEARCH_TERM = 'UPDATE_LOAN_SEARCH_TERM';
