// COPY LAST UPDATED BY DEV ON 2020/09/25

/* eslint-disable max-len */
export default [
	{
		year: '2005',
		title: 'Humble but strong beginnings',
		blurb: 'Kiva lenders make Kiva’s first loan to a woman named Elizabeth, who expanded her fishing business in Uganda. PayPal joins Kiva, providing free payment processing and ensuring 100% of every dollar lent goes to funding loans.',
		sticker: '2005-2.svg',
		cta1: 'Support a borrower like Elizabeth',
		cta2: 'Support borrowers like Elizabeth monthly',
		link1: '/lend-by-category/women',
		link2: '/monthlygood?category=women',
	},
	{
		year: '2006',
		title: 'Uplifting women entrepreneurs',
		blurb: 'After just one year the Kiva community has funded over $1 million in loans to women.',
		sticker: 'Repaid.svg',
		cta1: 'Lend to powerful women monthly',
		cta2: 'Lend to powerful women monthly',
		link1: '/monthlygood?category=women',
		link2: '/monthlygood?category=women',
	},
	{
		year: '2007',
		title: 'Microfinance—not just a textbook term',
		blurb: 'Over 130,000 lenders from 129 countries have joined Kiva, eager to make a difference through microfinance.',
		sticker: 'PlanetEarth.svg',
		cta1: 'Turn a microloan into a dream come true',
		cta2: 'Turn a microloan into a dream come true',
		link1: '/lend-by-category',
		link2: '/lend-by-category',
	},
	{
		year: '2008',
		title: 'One of the world\'s best',
		blurb: 'The Skoll Foundation grants Kiva $1 million, recognizing Kiva as one of the world’s best social enterprises.',
		sticker: 'Partner-1.svg',
		cta1: 'Let\'s partner up',
		cta2: 'Let\'s partner up',
		link1: 'https://kiva.global/strategic-partners/',
		link2: 'https://kiva.global/strategic-partners/',
	},
	{
		year: '2009',
		title: 'Lending a hand to 300,000 people',
		blurb: 'After four years, Kiva has funded nearly 300,000 borrowers and distributed over $112 million in loans.',
		sticker: 'BorrowerWeb.svg',
		cta1: 'Add another borrower to that list',
		cta2: 'Lend monthly',
		link1: '/lend-by-category',
		link2: '/monthlygood',
	},
	{
		year: '2010',
		title: 'Thanks, Oprah!',
		blurb: 'Oprah features Kiva on her show as "one of her ultimate favorite things." Omidyar Network awards $5 Million Grant to Kiva to spur growth of microfinance in underserved markets.',
		sticker: 'Megaphone.png',
		cta1: 'Lend like Oprah',
		cta2: 'Lend like Oprah',
		link1: '/lend-by-category',
		link2: '/lend-by-category',
	},
	{
		year: '2011',
		title: 'Scaling impact in America',
		blurb: 'Kiva U.S. launches and lenders quickly fund the first loan to a U.S. entrepreneur.',
		sticker: 'US-Map-1.png',
		cta1: 'Support an American entrepreneur',
		cta2: 'Support U.S. businesses monthly',
		link1: '/lend-by-category/kiva-u-s',
		link2: '/monthlygood?category=us_borrowers',
	},
	{
		year: '2012',
		title: 'Half a million supported',
		blurb: 'After just seven years, Kiva has funded 500,000 borrowers in 73 different countries, thanks to a large network of Field Partners and lenders.',
		sticker: 'BorrowerWeb-2.svg',
		cta1: 'Join the network and make an impact',
		cta2: 'Join the network and make an impact',
		link1: '/lend-by-category',
		link2: '/lend-by-category',
	},
	{
		year: '2013',
		title: 'Joining forces for good',
		blurb: 'Google grants Kiva a $3 million Global Impact Award to fund Kiva Labs, an innovative program investing in social enterprises. With Hewlett-Packard, Kiva launches a $7 million campaign called “Matter to a Million.”',
		sticker: 'Handshake.svg',
		cta1: 'Invest in a borrower monthly',
		cta2: 'Invest in a borrower monthly',
		link1: '/monthlygood',
		link2: '/monthlygood',
	},
	{
		year: '2014',
		title: '1.5 million borrowers supported',
		blurb: 'After nearly a decade, Kiva reaches over 800,000 loans. Kiva\'s lenders have reached over a million borrowers in thousands of communities around the world.',
		sticker: 'Hearts01.svg',
		cta1: 'Make an impact',
		cta2: 'Make an impact',
		link1: '/lend-by-category',
		link2: '/lend-by-category',
	},
	{
		year: '2015',
		title: 'One decade later...',
		blurb: 'The Kiva community has over 1.4 million lenders from 224 countries who have funded 1 million loans to nearly 2 million borrowers.',
		sticker: 'Money02.png',
		cta1: 'Join the crowd',
		cta2: 'Join the crowd and lend monthly',
		link1: '/lend-by-category',
		link2: '/monthlygood',
	},
	{
		year: '2016',
		title: 'Building opportunity for refugees',
		blurb: 'Kiva launches a $250,000 matching fund to provide support to refugees and the communities hosting them. These funds go to countries including Lebanon, Jordan, and Turkey.',
		sticker: 'Hearts02.svg',
		cta1: 'Support refugees’ path to stability',
		cta2: 'Support refugees monthly',
		link1: 'lend-by-category/conflict-zones',
		link2: '/monthlygood?category=refugees',
	},
	{
		year: '2017',
		title: '2.8 million borrowers funded',
		blurb: '1.4 million loans have been funded around the world after 12 years as an organization. Kiva loans have an incredible 96% repayment rate.',
		sticker: 'Repayment-2.svg',
		cta1: 'Fund a loan',
		cta2: 'Fund a loan',
		link1: '/lend-by-category',
		link2: '/lend-by-category',
	},
	{
		year: '2018',
		title: 'Hello, United Nations!',
		blurb: 'Kiva, the Sierra Leone government, and United Nations announce the establishment of Kiva Protocol at the U.N. General Assembly. This will help millions of Sierra Leonians establish their digital identity and access more financial resources.',
		sticker: 'SierraLeone.svg',
		cta1: 'Lend monthly',
		cta2: 'Lend monthly',
		link1: '/monthlygood',
		link2: '/monthlygood',
	},
	{
		year: '2019',
		title: 'A billion to women and a big launch in Sierra Leone',
		blurb: 'Kiva hit one of its biggest milestones ever: raising $1 BILLION in loans to women around the world. Meanwhile in Sierra Leone, Kiva Protocol launches to  help millions access more financial resources.',
		sticker: 'Palm02.svg',
		cta1: 'Be part of the next billion',
		cta2: 'Be part of the next billion',
		link1: '/monthlygood?category=women',
		link2: '/monthlygood?category=women',
	},
	{
		year: '2020',
		title: 'Big moves in a changing world',
		blurb: 'Amidst an unprecedented global pandemic, Kiva has raised over $70 million over 5 months to help 70,000 people. The team continues to innovate, launching the Kiva app for Apple iOS and Google\'s Android.',
		sticker: 'Colibrik-1.png',
		cta1: 'Be the difference for a borrower today',
		cta2: 'Be the difference for a borrower today',
		link1: '/lend-by-category',
		link2: '/monthlygood',
	}
];
