export default [
	{ path: '/ui-site-map', component: () => import('@/pages/UiSiteMap/UiSiteMapPage') },
	{ path: '/component-demo', component: () => import('@/pages/ComponentDemo/ComponentDemo') },
	{ path: '/kiva-app-components', component: () => import('@/pages/ComponentDemo/ComponentDemoKivaApp') },
	{ path: '/lend-vue', component: () => import('@/pages/Lend/LendPage') },
	{ path: '/lend-by-category', component: () => import('@/pages/Lend/LendByCategoryPage') },
	{ path: '/portfolio/lending-stats', component: () => import('@/pages/LendingStats/LendingStatsPage') },
	{ path: '/styleguide', component: () => import('@/pages/StyleGuide') },
	{ path: '/page-two', component: () => import('@/pages/PageTwo') },
	{ path: '/UI_REVISION', component: () => import('@/pages/UiRevision') },
	{ path: '/login-vue', component: () => import('@/pages/LoginAndRegister/LoginAndRegister') },
	{ path: '/checkout-vue', component: () => import('@/pages/Checkout/CheckoutPage') },
	{ path: '/checkout', component: () => import('@/pages/Checkout/CheckoutBetaPage') },
	{ path: '/protocol', component: () => import('@/pages/Protocol') },
	{ path: '/build', component: () => import('@/pages/Build/BuildPage') },
	{ path: '/build/docs', component: () => import('@/pages/Build/DocsPage') },
	{ path: '/build/code-of-conduct', component: () => import('@/pages/Build/CodeOfConductPage') },
	{ path: '/algolia-vue', component: () => import('@/pages/AlgoliaPOC') },
];
