query MyDonations($offset: Int = 0, $limit: Int = 10, $sortBy: DonationSortEnum = newest) {
    my {
		id
        userAccount {
			id
            donationInfo {
                fullDonorName
                currentYear
                currentYearDonations
                hasDafDonations
                latestTaxYear
                latestTaxYearDonations
                annualDonations {
                    year
                    total
                }
            }
            donationEntries(offset: $offset, limit: $limit, sortBy: $sortBy) {
                total
                donations {
                    id
                    price
                    completedTime
                }
            }
        }
    }
}
