module.exports = [
	'auto-deposit',
	'checkout',
	'confirm-instant-donation',
	'instant-donation-thanks',
	'instant-lending-error',
	'lend/saved-search',
	'monthlygood/setup',
	'monthlygood/thanks',
	'join-team',
	'portfolio',
	'process-instant-lending',
	'process-browser-auth',
	'register',
	'settings',
	'start-verification',
	'UI_REVISION',
	'ui-site-map'
];
