name: Docker Build Test

on:
  pull_request:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: "us-west-2"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  GITHUB_PAT: "${{ secrets.KIVA_ROBOT_GITHUB_PAT }}"
  SLACK_BOT_TOKEN: "${{ secrets.SLACK_TOKEN }}"
  SLACK_CHANNEL: "eng-build-failures"

jobs:
  # Test that the image actually builds on each commit
  build-push-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_PAT }}
      - uses: actions/checkout@v3
        with:
          repository: kiva/github-actions
          token: ${{ env.GITHUB_PAT }}
          path: .github/
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          repository: kiva/marketplace-web-ui-ci
          token: ${{ env.GITHUB_PAT }}
          path: .docker
          ref: main
          patterns: |
            resources/org/kiva/marketplaceWebUiCi/ui

      - name: move files
        run: |
          mv .docker/resources/org/kiva/marketplaceWebUiCi/ui/Dockerfile .
          cp -aRv .docker/resources/org/kiva/marketplaceWebUiCi/ui/config .

      - name: docker-build
        uses: ./.github/actions/docker-build-push
        if: github.event_name == 'pull_request'
        with:
          build_args: |
            TARGET_ENV=dev
          dockerfile_target: "release"
          push: false
