name: create-release

on:
  workflow_dispatch:
    inputs:
      pre_release:
        description: "Should this be a pre-release for staging?"
        required: true
        type: boolean
        default: true
      pre_release_branch:
        description: "Branch to use for pre-release"
        required: false
        type: string
        default: "main"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.KIVA_ROBOT_GITHUB_PAT }}
      - name: checkout-actions
        uses: actions/checkout@v4
        with:
          repository: kiva/github-actions
          token: ${{ secrets.KIVA_ROBOT_GITHUB_PAT }}
          path: .github/
      - name: create-release
        id: release
        uses: ./.github/actions/start-semantic-release
        env:
          GITHUB_PAT: ${{ secrets.KIVA_ROBOT_GITHUB_PAT }}
        with:
          pre_release: "${{ github.event.inputs.pre_release }}"
          pre_release_branch: ${{ github.event.inputs.pre_release_branch }}
