name: Lighthouse CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: ./lighthouserc.js
          serverBaseUrl: https://lighthouse-ci-kiva-dev.herokuapp.com/
          serverToken: ${{ secrets.LHCI_DEV_BUILD_TOKEN }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
