name: Lint PR (semantic title)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: kiva/github-actions
          token: ${{ secrets.KIVA_ROBOT_GITHUB_PAT }}
          path: .github/
      - name: lint-pr
        uses: ./.github/actions/lint-pr
        env:
          GITHUB_PAT: ${{ secrets.KIVA_ROBOT_GITHUB_PAT }}
