name: Release
on:
  push:
    branches:
      - main
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --yes -p conventional-changelog-conventionalcommits@4 -p @semantic-release/changelog@6 -p @semantic-release/git@10 -p semantic-release@18 semantic-release
